{
 "title": "Reports",
 "time": { "from": "2016-09-01T00:00:00.000Z", "to": "2017-08-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "Neighbourhoods with max visits per property",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with airbnb_base as (\n\tselect *, (price * minimum_nights * number_of_reviews) as min_earnings  from airbnb_data_ny adn \n),\nairbnb_summary as (\n\tselect neighbourhood,\n\t\t   (sum(number_of_reviews) / count(*)) as visits_per_property\n\tfrom airbnb_base\n\tgroup by neighbourhood\n\torder by visits_per_property desc\n)\nselect * from airbnb_summary LIMIT 100;"
    }
   ]
  },
  {
   "title": "Expensive neighbourhoods by property price",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "with residential_buildings as (\n\tselect * from property_sales_ny as psy where residential_units > commercial_units\n),\nvalid_sales as (\n\tselect * from residential_buildings rb \n\twhere sale_price is not null \n\tand sale_price > 10000\n\tand gross_square_feet is not null and gross_square_feet > 0\n\tand land_square_feet is not null and land_square_feet > 0\n),\nproperty_sales_summary as (\n\tselect neighborhood, round((sum(sale_price) / count(*))) as avg_property_price\n\tfrom valid_sales\n\tgroup by neighborhood\n)\nselect * from property_sales_summary limit 20;"
    }
   ]
  },
  {
   "title": "Top neighbourhoods by PropertyCount, with Avg prices",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select neighbourhood, count(*) as property_count, avg(price) as avg_price_per_night from airbnb_data_ny\ngroup by neighbourhood\norder by property_count desc;"
    }
   ]
  },
  {
   "title": "Most expensive neighbourhoods with their property counts",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select neighbourhood, count(*) as property_count, avg(price) as avg_price_per_night from airbnb_data_ny\ngroup by neighbourhood\norder by avg_price_per_night desc;"
    }
   ]
  },
  {
   "title": "Most Common Price Range",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "\nwith base as (\nSELECT (\n  CASE \n    WHEN price >= 0 AND price <= 50 THEN '0-50'\n    WHEN price > 50 AND price <= 100 THEN '50-100'\n    WHEN price > 100 AND price <= 150 THEN '100-150'\n\tWHEN price > 150 AND price <= 200 THEN '100-150'\n    WHEN price > 200 AND price <= 250 THEN '200-250'\n    WHEN price > 250 AND price <= 300 THEN '250-300'    \n    WHEN price > 300 AND price <= 350 THEN '300-350'    \n    WHEN price > 350 AND price <= 400 THEN '350-400'\n    WHEN price > 400 AND price <= 450 THEN '350-400'\n    WHEN price > 450 AND price <= 500 THEN '450-500'    \n    WHEN price > 500 AND price <= 550 THEN '500-550'\n    WHEN price > 550 AND price <= 600 THEN '550-600'\n    WHEN price > 600 AND price <= 650 THEN '600-650'\n    WHEN price > 650 AND price <= 700 THEN '650-700'\n    WHEN price > 700 AND price <= 750 THEN '700-750'    \n    WHEN price > 750 AND price <= 1000 THEN '750-1000'\n    WHEN price > 1000 AND price <= 10000 THEN '1000-10000'    \n  END\n) as price_range, count(*) as property_count\nfrom airbnb_data_ny adn\ngroup by price_range\n)\nselect * from base order by length(price_range), price_range;"
    }
   ]
  },
  {
   "title": "Popular and Expensive categories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expensive categories by sales",
     "type": "barchart",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "rawSql": "select \n\tsubstring(psdny.building_class_category, 0, 10) AS category,\n\tsum(sale_price) / count(*) as avg_unit_price \nfrom property_sales_ny psdny \nwhere sale_price is not null and sale_price > 0\ngroup by building_class_category \norder by avg_unit_price desc;\n"
      }
     ]
    },
    {
     "title": "Popular categories by sales",
     "type": "piechart",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select \n\tpsdny.building_class_category as category, count(*) as total_sales\nfrom property_sales_ny psdny \nwhere sale_price is not null and sale_price > 0\ngroup by building_class_category \norder by total_sales desc limit 10;"
      }
     ]
    }
   ]
  },
  { "title": "Sales and week dependence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Week on week sales to temp",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "with base_temp_table as (\n\tselect \n\t\ttimestamp, ROW_NUMBER () OVER ( ORDER BY timestamp) as rn, mean, max, min\n\tFROM\n\t\tweather_data as wd\n\tORDER BY timestamp\n),\ntemp_by_week as (\n\tselect ceil(rn / 7) as week, avg(mean) as avg_temp from base_temp_table\n\tgroup by week\n\torder by week\n),\nwith_temp_lag as (\n\tselect *, lag(avg_temp) over(order by week) as previous_week_temp from temp_by_week\t\n),\nbase_ps_table as (\n\tselect \n\t\tps.sale_date, count(*) as total_sales_per_day\n\tFROM\n\t\tproperty_sales_ny as ps\n\t\n\twhere sale_date is not NULL\t\t\n\tgroup by sale_date\n\t\n), temp_ps_table as (\n\tselect *, ROW_NUMBER () OVER ( ORDER BY sale_date) as rn from base_ps_table order by sale_date\n),\nsales_per_week as (\n\tselect ceil(rn / 7) as week, sum(total_sales_per_day) as total_sales from temp_ps_table\n\tgroup by week\n\torder by week\n),\nwith_sales_lag as (\n\tselect *, lag(total_sales) over(order by week) as previous_week_sales from sales_per_week \n)\nselect week::varchar(255), \n\t  ((avg_temp - previous_week_temp) / previous_week_temp) * 100 as wow_temp,\n\t  ((total_sales - previous_week_sales) / previous_week_sales) * 100 as wow_sales\nfrom with_sales_lag join with_temp_lag\nusing(week)\norder by week::integer;"
    }
   ]
  },
  {
   "title": "Sales vs Temp by week",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "with base_temp_table as (\n\tselect \n\t\ttimestamp, ROW_NUMBER () OVER ( ORDER BY timestamp) as rn, mean, max, min\n\tFROM\n\t\tweather_data as wd\n\tORDER BY timestamp\n),\ntemp_by_week as (\n\tselect ceil(rn / 7) as week, avg(mean) as avg_temp from base_temp_table\n\tgroup by week\n\torder by week\n),\nbase_ps_table as (\n\tselect \n\t\tps.sale_date, count(*) as total_sales_per_day\n\tFROM\n\t\tproperty_sales_ny as ps\n\t\n\twhere sale_date is not NULL\t\t\n\tgroup by sale_date\n\t\n), temp_ps_table as (\n\tselect *, ROW_NUMBER () OVER ( ORDER BY sale_date) as rn from base_ps_table order by sale_date\n),\nsales_per_week as (\n\tselect ceil(rn / 7) as week, sum(total_sales_per_day) as total_sales from temp_ps_table\n\tgroup by week\n\torder by week\n)\nselect sw.week::varchar(255), total_sales, avg_temp from sales_per_week as sw\njoin temp_by_week as tw on sw.week = tw.week\norder by sw.week;"
    }
   ]
  }
 ]
}